//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.23 at 07:45:34 PM CDT 
//


package https.www_wcio_org.xml.wcstat;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataTypeCode_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DataTypeCode_Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="WCA"/&gt;
 *     &lt;enumeration value="WCC"/&gt;
 *     &lt;enumeration value="WCE"/&gt;
 *     &lt;enumeration value="WCF"/&gt;
 *     &lt;enumeration value="WCG"/&gt;
 *     &lt;enumeration value="WCI"/&gt;
 *     &lt;enumeration value="WCL"/&gt;
 *     &lt;enumeration value="WCM"/&gt;
 *     &lt;enumeration value="WCN"/&gt;
 *     &lt;enumeration value="WCO"/&gt;
 *     &lt;enumeration value="WCP"/&gt;
 *     &lt;enumeration value="WCR"/&gt;
 *     &lt;enumeration value="WCS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DataTypeCode_Type")
@XmlEnum
public enum DataTypeCodeType {

    WCA,
    WCC,
    WCE,
    WCF,
    WCG,
    WCI,
    WCL,
    WCM,
    WCN,
    WCO,
    WCP,
    WCR,
    WCS;

    public String value() {
        return name();
    }

    public static DataTypeCodeType fromValue(String v) {
        return valueOf(v);
    }

}
