//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.23 at 07:45:34 PM CDT 
//


package https.www_wcio_org.xml.wcstat;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OrganizationName" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *         &lt;element name="SeparatedNameOfInsured" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="nameReference" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "organizationName",
    "separatedNameOfInsured"
})
@XmlRootElement(name = "Name")
@Entity(name = "Name")
@Table(name = "NAME_")
@Inheritance(strategy = InheritanceType.JOINED)
public class Name
    implements Equals, HashCode
{

    @XmlElement(name = "OrganizationName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String organizationName;
    @XmlElement(name = "SeparatedNameOfInsured")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String separatedNameOfInsured;
    @XmlAttribute(name = "nameReference")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String nameReference;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the organizationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ORGANIZATION_NAME", length = 255)
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * Sets the value of the organizationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationName(String value) {
        this.organizationName = value;
    }

    /**
     * Gets the value of the separatedNameOfInsured property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "SEPARATED_NAME_OF_INSURED", length = 255)
    public String getSeparatedNameOfInsured() {
        return separatedNameOfInsured;
    }

    /**
     * Sets the value of the separatedNameOfInsured property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeparatedNameOfInsured(String value) {
        this.separatedNameOfInsured = value;
    }

    /**
     * Gets the value of the nameReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "NAME_REFERENCE", length = 255)
    public String getNameReference() {
        return nameReference;
    }

    /**
     * Sets the value of the nameReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameReference(String value) {
        this.nameReference = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Name that = ((Name) object);
        {
            String lhsOrganizationName;
            lhsOrganizationName = this.getOrganizationName();
            String rhsOrganizationName;
            rhsOrganizationName = that.getOrganizationName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "organizationName", lhsOrganizationName), LocatorUtils.property(thatLocator, "organizationName", rhsOrganizationName), lhsOrganizationName, rhsOrganizationName)) {
                return false;
            }
        }
        {
            String lhsSeparatedNameOfInsured;
            lhsSeparatedNameOfInsured = this.getSeparatedNameOfInsured();
            String rhsSeparatedNameOfInsured;
            rhsSeparatedNameOfInsured = that.getSeparatedNameOfInsured();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "separatedNameOfInsured", lhsSeparatedNameOfInsured), LocatorUtils.property(thatLocator, "separatedNameOfInsured", rhsSeparatedNameOfInsured), lhsSeparatedNameOfInsured, rhsSeparatedNameOfInsured)) {
                return false;
            }
        }
        {
            String lhsNameReference;
            lhsNameReference = this.getNameReference();
            String rhsNameReference;
            rhsNameReference = that.getNameReference();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nameReference", lhsNameReference), LocatorUtils.property(thatLocator, "nameReference", rhsNameReference), lhsNameReference, rhsNameReference)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theOrganizationName;
            theOrganizationName = this.getOrganizationName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "organizationName", theOrganizationName), currentHashCode, theOrganizationName);
        }
        {
            String theSeparatedNameOfInsured;
            theSeparatedNameOfInsured = this.getSeparatedNameOfInsured();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "separatedNameOfInsured", theSeparatedNameOfInsured), currentHashCode, theSeparatedNameOfInsured);
        }
        {
            String theNameReference;
            theNameReference = this.getNameReference();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nameReference", theNameReference), currentHashCode, theNameReference);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
