//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.23 at 07:45:34 PM CDT 
//


package https.www_wcio_org.xml.wcstat;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.www_wcio_org.xml.wcstat package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.www_wcio_org.xml.wcstat
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Submission }
     * 
     */
    public Submission createSubmission() {
        return new Submission();
    }

    /**
     * Create an instance of {@link Submission.Wcstats }
     * 
     */
    public Submission.Wcstats createSubmissionWcstats() {
        return new Submission.Wcstats();
    }

    /**
     * Create an instance of {@link Submission.Wcstats.Wcstat }
     * 
     */
    public Submission.Wcstats.Wcstat createSubmissionWcstatsWcstat() {
        return new Submission.Wcstats.Wcstat();
    }

    /**
     * Create an instance of {@link Submission.Wcstats.Wcstat.Losses }
     * 
     */
    public Submission.Wcstats.Wcstat.Losses createSubmissionWcstatsWcstatLosses() {
        return new Submission.Wcstats.Wcstat.Losses();
    }

    /**
     * Create an instance of {@link Submission.Wcstats.Wcstat.Losses.Loss }
     * 
     */
    public Submission.Wcstats.Wcstat.Losses.Loss createSubmissionWcstatsWcstatLossesLoss() {
        return new Submission.Wcstats.Wcstat.Losses.Loss();
    }

    /**
     * Create an instance of {@link Submission.Wcstats.Wcstat.Losses.Loss.Beneficiaries }
     * 
     */
    public Submission.Wcstats.Wcstat.Losses.Loss.Beneficiaries createSubmissionWcstatsWcstatLossesLossBeneficiaries() {
        return new Submission.Wcstats.Wcstat.Losses.Loss.Beneficiaries();
    }

    /**
     * Create an instance of {@link Submission.Wcstats.Wcstat.Losses.Loss.ScheduledIndemnities }
     * 
     */
    public Submission.Wcstats.Wcstat.Losses.Loss.ScheduledIndemnities createSubmissionWcstatsWcstatLossesLossScheduledIndemnities() {
        return new Submission.Wcstats.Wcstat.Losses.Loss.ScheduledIndemnities();
    }

    /**
     * Create an instance of {@link Submission.Wcstats.Wcstat.Exposures }
     * 
     */
    public Submission.Wcstats.Wcstat.Exposures createSubmissionWcstatsWcstatExposures() {
        return new Submission.Wcstats.Wcstat.Exposures();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Transmittal }
     * 
     */
    public Transmittal createTransmittal() {
        return new Transmittal();
    }

    /**
     * Create an instance of {@link Submission.FileControl }
     * 
     */
    public Submission.FileControl createSubmissionFileControl() {
        return new Submission.FileControl();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link Submission.Wcstats.Wcstat.Insured }
     * 
     */
    public Submission.Wcstats.Wcstat.Insured createSubmissionWcstatsWcstatInsured() {
        return new Submission.Wcstats.Wcstat.Insured();
    }

    /**
     * Create an instance of {@link Submission.Wcstats.Wcstat.Losses.Loss.Beneficiaries.Beneficiary }
     * 
     */
    public Submission.Wcstats.Wcstat.Losses.Loss.Beneficiaries.Beneficiary createSubmissionWcstatsWcstatLossesLossBeneficiariesBeneficiary() {
        return new Submission.Wcstats.Wcstat.Losses.Loss.Beneficiaries.Beneficiary();
    }

    /**
     * Create an instance of {@link Submission.Wcstats.Wcstat.Losses.Loss.ScheduledIndemnities.ScheduledIndemnity }
     * 
     */
    public Submission.Wcstats.Wcstat.Losses.Loss.ScheduledIndemnities.ScheduledIndemnity createSubmissionWcstatsWcstatLossesLossScheduledIndemnitiesScheduledIndemnity() {
        return new Submission.Wcstats.Wcstat.Losses.Loss.ScheduledIndemnities.ScheduledIndemnity();
    }

    /**
     * Create an instance of {@link Submission.Wcstats.Wcstat.Exposures.Exposure }
     * 
     */
    public Submission.Wcstats.Wcstat.Exposures.Exposure createSubmissionWcstatsWcstatExposuresExposure() {
        return new Submission.Wcstats.Wcstat.Exposures.Exposure();
    }

}
