//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.23 at 07:45:34 PM CDT 
//


package referencedatamodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the referencedatamodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReferenceData_QNAME = new QName("http://guidewire.com/bc/gx/referencedatamodel", "ReferenceData");
    private final static QName _ReferenceDataDataType_QNAME = new QName("http://guidewire.com/bc/gx/referencedatamodel", "DataType");
    private final static QName _ReferenceDataLength_QNAME = new QName("http://guidewire.com/bc/gx/referencedatamodel", "Length");
    private final static QName _ReferenceDataPrecision_QNAME = new QName("http://guidewire.com/bc/gx/referencedatamodel", "Precision");
    private final static QName _ReferenceDataScale_QNAME = new QName("http://guidewire.com/bc/gx/referencedatamodel", "Scale");
    private final static QName _ReferenceDataSchemaElementName_QNAME = new QName("http://guidewire.com/bc/gx/referencedatamodel", "SchemaElementName");
    private final static QName _ReferenceDataSubjectHeaders_QNAME = new QName("http://guidewire.com/bc/gx/referencedatamodel", "SubjectHeaders");
    private final static QName _ReferenceDataTypeName_QNAME = new QName("http://guidewire.com/bc/gx/referencedatamodel", "TypeName");
    private final static QName _ReferenceDataWCStatElementName_QNAME = new QName("http://guidewire.com/bc/gx/referencedatamodel", "WCStatElementName");
    private final static QName _ReferenceDataSubjectHeadersSubjectHeaderEndPosition_QNAME = new QName("http://guidewire.com/bc/gx/referencedatamodel", "EndPosition");
    private final static QName _ReferenceDataSubjectHeadersSubjectHeaderStartPosition_QNAME = new QName("http://guidewire.com/bc/gx/referencedatamodel", "StartPosition");
    private final static QName _ReferenceDataSubjectHeadersSubjectHeaderStates_QNAME = new QName("http://guidewire.com/bc/gx/referencedatamodel", "States");
    private final static QName _ReferenceDataSubjectHeadersSubjectHeaderSubjectHeader_QNAME = new QName("http://guidewire.com/bc/gx/referencedatamodel", "SubjectHeader");
    private final static QName _ReferenceDataSubjectHeadersSubjectHeaderStatesStateNameOfTheState_QNAME = new QName("http://guidewire.com/bc/gx/referencedatamodel", "NameOfTheState");
    private final static QName _ReferenceDataSubjectHeadersSubjectHeaderStatesStateStateCode_QNAME = new QName("http://guidewire.com/bc/gx/referencedatamodel", "StateCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: referencedatamodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReferenceData }
     * 
     */
    public ReferenceData createReferenceData() {
        return new ReferenceData();
    }

    /**
     * Create an instance of {@link ReferenceData.SubjectHeaders }
     * 
     */
    public ReferenceData.SubjectHeaders createReferenceDataSubjectHeaders() {
        return new ReferenceData.SubjectHeaders();
    }

    /**
     * Create an instance of {@link ReferenceData.SubjectHeaders.SubjectHeader }
     * 
     */
    public ReferenceData.SubjectHeaders.SubjectHeader createReferenceDataSubjectHeadersSubjectHeader() {
        return new ReferenceData.SubjectHeaders.SubjectHeader();
    }

    /**
     * Create an instance of {@link ReferenceData.SubjectHeaders.SubjectHeader.States }
     * 
     */
    public ReferenceData.SubjectHeaders.SubjectHeader.States createReferenceDataSubjectHeadersSubjectHeaderStates() {
        return new ReferenceData.SubjectHeaders.SubjectHeader.States();
    }

    /**
     * Create an instance of {@link ReferenceData.SubjectHeaders.SubjectHeader.States.State }
     * 
     */
    public ReferenceData.SubjectHeaders.SubjectHeader.States.State createReferenceDataSubjectHeadersSubjectHeaderStatesState() {
        return new ReferenceData.SubjectHeaders.SubjectHeader.States.State();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/referencedatamodel", name = "ReferenceData")
    public JAXBElement<ReferenceData> createReferenceData(ReferenceData value) {
        return new JAXBElement<ReferenceData>(_ReferenceData_QNAME, ReferenceData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/referencedatamodel", name = "DataType", scope = ReferenceData.class)
    public JAXBElement<Integer> createReferenceDataDataType(Integer value) {
        return new JAXBElement<Integer>(_ReferenceDataDataType_QNAME, Integer.class, ReferenceData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/referencedatamodel", name = "Length", scope = ReferenceData.class)
    public JAXBElement<Integer> createReferenceDataLength(Integer value) {
        return new JAXBElement<Integer>(_ReferenceDataLength_QNAME, Integer.class, ReferenceData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/referencedatamodel", name = "Precision", scope = ReferenceData.class)
    public JAXBElement<Integer> createReferenceDataPrecision(Integer value) {
        return new JAXBElement<Integer>(_ReferenceDataPrecision_QNAME, Integer.class, ReferenceData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/referencedatamodel", name = "Scale", scope = ReferenceData.class)
    public JAXBElement<Integer> createReferenceDataScale(Integer value) {
        return new JAXBElement<Integer>(_ReferenceDataScale_QNAME, Integer.class, ReferenceData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/referencedatamodel", name = "SchemaElementName", scope = ReferenceData.class)
    public JAXBElement<String> createReferenceDataSchemaElementName(String value) {
        return new JAXBElement<String>(_ReferenceDataSchemaElementName_QNAME, String.class, ReferenceData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceData.SubjectHeaders }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/referencedatamodel", name = "SubjectHeaders", scope = ReferenceData.class)
    public JAXBElement<ReferenceData.SubjectHeaders> createReferenceDataSubjectHeaders(ReferenceData.SubjectHeaders value) {
        return new JAXBElement<ReferenceData.SubjectHeaders>(_ReferenceDataSubjectHeaders_QNAME, ReferenceData.SubjectHeaders.class, ReferenceData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/referencedatamodel", name = "TypeName", scope = ReferenceData.class)
    public JAXBElement<String> createReferenceDataTypeName(String value) {
        return new JAXBElement<String>(_ReferenceDataTypeName_QNAME, String.class, ReferenceData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/referencedatamodel", name = "WCStatElementName", scope = ReferenceData.class)
    public JAXBElement<String> createReferenceDataWCStatElementName(String value) {
        return new JAXBElement<String>(_ReferenceDataWCStatElementName_QNAME, String.class, ReferenceData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/referencedatamodel", name = "EndPosition", scope = ReferenceData.SubjectHeaders.SubjectHeader.class)
    public JAXBElement<String> createReferenceDataSubjectHeadersSubjectHeaderEndPosition(String value) {
        return new JAXBElement<String>(_ReferenceDataSubjectHeadersSubjectHeaderEndPosition_QNAME, String.class, ReferenceData.SubjectHeaders.SubjectHeader.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/referencedatamodel", name = "Length", scope = ReferenceData.SubjectHeaders.SubjectHeader.class)
    public JAXBElement<String> createReferenceDataSubjectHeadersSubjectHeaderLength(String value) {
        return new JAXBElement<String>(_ReferenceDataLength_QNAME, String.class, ReferenceData.SubjectHeaders.SubjectHeader.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/referencedatamodel", name = "StartPosition", scope = ReferenceData.SubjectHeaders.SubjectHeader.class)
    public JAXBElement<String> createReferenceDataSubjectHeadersSubjectHeaderStartPosition(String value) {
        return new JAXBElement<String>(_ReferenceDataSubjectHeadersSubjectHeaderStartPosition_QNAME, String.class, ReferenceData.SubjectHeaders.SubjectHeader.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceData.SubjectHeaders.SubjectHeader.States }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/referencedatamodel", name = "States", scope = ReferenceData.SubjectHeaders.SubjectHeader.class)
    public JAXBElement<ReferenceData.SubjectHeaders.SubjectHeader.States> createReferenceDataSubjectHeadersSubjectHeaderStates(ReferenceData.SubjectHeaders.SubjectHeader.States value) {
        return new JAXBElement<ReferenceData.SubjectHeaders.SubjectHeader.States>(_ReferenceDataSubjectHeadersSubjectHeaderStates_QNAME, ReferenceData.SubjectHeaders.SubjectHeader.States.class, ReferenceData.SubjectHeaders.SubjectHeader.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/referencedatamodel", name = "SubjectHeader", scope = ReferenceData.SubjectHeaders.SubjectHeader.class)
    public JAXBElement<String> createReferenceDataSubjectHeadersSubjectHeaderSubjectHeader(String value) {
        return new JAXBElement<String>(_ReferenceDataSubjectHeadersSubjectHeaderSubjectHeader_QNAME, String.class, ReferenceData.SubjectHeaders.SubjectHeader.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/referencedatamodel", name = "NameOfTheState", scope = ReferenceData.SubjectHeaders.SubjectHeader.States.State.class)
    public JAXBElement<String> createReferenceDataSubjectHeadersSubjectHeaderStatesStateNameOfTheState(String value) {
        return new JAXBElement<String>(_ReferenceDataSubjectHeadersSubjectHeaderStatesStateNameOfTheState_QNAME, String.class, ReferenceData.SubjectHeaders.SubjectHeader.States.State.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/referencedatamodel", name = "StateCode", scope = ReferenceData.SubjectHeaders.SubjectHeader.States.State.class)
    public JAXBElement<String> createReferenceDataSubjectHeadersSubjectHeaderStatesStateStateCode(String value) {
        return new JAXBElement<String>(_ReferenceDataSubjectHeadersSubjectHeaderStatesStateStateCode_QNAME, String.class, ReferenceData.SubjectHeaders.SubjectHeader.States.State.class, value);
    }

}
