//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.23 at 07:45:34 PM CDT 
//


package reportschedulemodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the reportschedulemodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReportSchedule_QNAME = new QName("http://guidewire.com/bc/gx/reportschedulemodel", "ReportSchedule");
    private final static QName _ReportScheduleDateOfEvaluation_QNAME = new QName("http://guidewire.com/bc/gx/reportschedulemodel", "DateOfEvaluation");
    private final static QName _ReportScheduleDateOfReporting_QNAME = new QName("http://guidewire.com/bc/gx/reportschedulemodel", "DateOfReporting");
    private final static QName _ReportScheduleReportLevel_QNAME = new QName("http://guidewire.com/bc/gx/reportschedulemodel", "ReportLevel");
    private final static QName _ReportScheduleReportNumber_QNAME = new QName("http://guidewire.com/bc/gx/reportschedulemodel", "ReportNumber");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: reportschedulemodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReportSchedule }
     * 
     */
    public ReportSchedule createReportSchedule() {
        return new ReportSchedule();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReportSchedule }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/reportschedulemodel", name = "ReportSchedule")
    public JAXBElement<ReportSchedule> createReportSchedule(ReportSchedule value) {
        return new JAXBElement<ReportSchedule>(_ReportSchedule_QNAME, ReportSchedule.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/reportschedulemodel", name = "DateOfEvaluation", scope = ReportSchedule.class)
    public JAXBElement<Integer> createReportScheduleDateOfEvaluation(Integer value) {
        return new JAXBElement<Integer>(_ReportScheduleDateOfEvaluation_QNAME, Integer.class, ReportSchedule.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/reportschedulemodel", name = "DateOfReporting", scope = ReportSchedule.class)
    public JAXBElement<Integer> createReportScheduleDateOfReporting(Integer value) {
        return new JAXBElement<Integer>(_ReportScheduleDateOfReporting_QNAME, Integer.class, ReportSchedule.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/reportschedulemodel", name = "ReportLevel", scope = ReportSchedule.class)
    public JAXBElement<String> createReportScheduleReportLevel(String value) {
        return new JAXBElement<String>(_ReportScheduleReportLevel_QNAME, String.class, ReportSchedule.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/reportschedulemodel", name = "ReportNumber", scope = ReportSchedule.class)
    public JAXBElement<String> createReportScheduleReportNumber(String value) {
        return new JAXBElement<String>(_ReportScheduleReportNumber_QNAME, String.class, ReportSchedule.class, value);
    }

}
