package dataprocessor;

public class Queries {
    public static String refmetadata =
            "SELECT" + " " +
                    "HEADERTYPE.TYPECODE AS SUBJECTHEADER,"  + " " +
                    "ELEMENTDETAILS.SCHEMAELEMENTNAME AS ELEMENTNAME," + " " +
                    "HEADERTYPE.TARGETSCHEMA AS TARGETSCHEMA,"  + " " +
                    "HEADERTYPE.TARGETTABLE AS TARGETTABLE,"  + " " +
                    "ELEMENTDETAILS.TYPENAME AS TYPENAME,"  + " " +
                    "SUBJECTHEADER.FILESTARTPOSITION AS STARTPOSITION,"  + " " +
                    "SUBJECTHEADER.FILEENDPOSITION AS ENDPOSITION,"  + " " +
                    "SUBJECTHEADER.ELEMENTLENGTH AS LENGTHOFELEMENT,"  + " " +
                    "SUBJECTHEADER.CLASS AS CLASS, " + " " +
                    "HEADERTYPE.RECORD_TYPE AS RECORDTYPE, " + " " +
                    "HEADERTYPE.RECORD_NUMBER_START_POSITION AS RECORD_NUMBER_START_POSITION, " + " "+
                    "HEADERTYPE.RECORD_NUMBER_LENGTH AS RECORD_NUMBER_LENGTH " + " " +
                    "FROM WCSTREF.NCCISUBJECTHEADER SUBJECTHEADER"  + " " +
                    "JOIN WCSTREF.NCCIELEMENTDETAILS ELEMENTDETAILS ON ELEMENTDETAILS.ID = SUBJECTHEADER.NCCIELEMENTDETAILSID"  + " " +
                    "JOIN WCSTREF.NCCISTATETOSUBJECTHEADER STATETOSUBJECTHEADER ON STATETOSUBJECTHEADER.NCCISUBJECTHEADER = SUBJECTHEADER.ID"  + " " +
                    "JOIN WCSTREF.NCCISUBJECTHEADERTYPE HEADERTYPE ON SUBJECTHEADER.NCCISUBJECTHEADERNAME = HEADERTYPE.ID"  + " " +
                    "LEFT JOIN WCSTREF.NCCI_STATE STATES ON STATETOSUBJECTHEADER.STATE = STATES.ID WHERE HEADERTYPE.TYPECODE IN (";

    public static String lenthandoffset =
                    "SELECT" + " " +
                    "SUBJECTHEADER.FILESTARTPOSITION AS STARTPOSITION,"  + " " +
                    "SUBJECTHEADER.FILEENDPOSITION AS ENDPOSITION,"  + " " +
                    "SUBJECTHEADER.ELEMENTLENGTH AS LENGTHOFELEMENT"  + " " +
                    "FROM WCSTREF.NCCISUBJECTHEADER SUBJECTHEADER"  + " " +
                    "JOIN WCSTREF.NCCIELEMENTDETAILS ELEMENTDETAILS ON ELEMENTDETAILS.ID = SUBJECTHEADER.NCCIELEMENTDETAILSID"  + " " +
                    "JOIN WCSTREF.NCCISTATETOSUBJECTHEADER STATETOSUBJECTHEADER ON STATETOSUBJECTHEADER.NCCISUBJECTHEADER = SUBJECTHEADER.ID"  + " " +
                    "JOIN WCSTREF.NCCISUBJECTHEADERTYPE HEADERTYPE ON SUBJECTHEADER.NCCISUBJECTHEADERNAME = HEADERTYPE.ID"  + " " +
                    "JOIN WCSTREF.NCCI_STATE STATES ON STATETOSUBJECTHEADER.STATE = STATES.ID WHERE ELEMENTDETAILS.SCHEMAELEMENTNAME =? AND HEADERTYPE.TYPECODE = ?";
    public static String loss =
            "SELECT " + "?" + " FROM WCSTAT.LINK_DATA LINK  JOIN WCSTAT.LOSS LOSS ON LOSS.LINKID = LINK.ID";

    public static String subjectHeader ="SELECT NAME AS NAME FROM WCSTREF.NCCISUBJECTHEADERTYPE";

    public static String byReport =
    "SELECT" +
    " ELEMENTDETAILS.WCSTATHANDBOOKNAME AS NCCIELEMENTNAME," +
    " SUBJECTHEADER.FILESTARTPOSITION AS NCCIELEMENTOFFSET," +
    " SUBJECTHEADER.FILEENDPOSITION AS  NCCIELEMMENTLENGTH," +
    " HEADERTYPE.NAME AS SUBJECTHEADER" +
    " FROM WCSTREF.NCCISUBJECTHEADER SUBJECTHEADER" +
    " JOIN WCSTREF.NCCIELEMENTDETAILS ELEMENTDETAILS ON ELEMENTDETAILS.ID = SUBJECTHEADER.NCCIELEMENTDETAILSID" +
    " LEFT JOIN WCSTREF.NCCISTATETOSUBJECTHEADER STATETOSUBJECTHEADER ON STATETOSUBJECTHEADER.NCCISUBJECTHEADER = SUBJECTHEADER.ID" +
    " JOIN WCSTREF.NCCI_STATE STATEES ON STATETOSUBJECTHEADER.STATE = STATEES.ID" +
    " JOIN WCSTREF.NCCISUBJECTHEADERTYPE HEADERTYPE ON HEADERTYPE.ID =  SUBJECTHEADER.NCCISUBJECTHEADERNAME" +
    " WHERE HEADERTYPE.NAME IN ('ADDRESS RECORD', 'EXPOSURE RECORD', 'FILE CONTROL RECORD'," +
    " 'HEADER RECORD', 'LINK DATA COMMON TO ALL RECORDS', 'LOSS RECORD', 'NAME RECORD' , 'UNIT TOTAL RECORD' )" +
    " ORDER BY HEADERTYPE.RECORD_TYPE, SUBJECTHEADER.FILESTARTPOSITION;";
    public static String byState =
    "SELECT ELEMENTDETAILS.WCSTATHANDBOOKNAME AS NCCIELEMENTNAME," +
    " SUBJECTHEADER.FILESTARTPOSITION AS NCCIELEMENTOFFSET," +
    " SUBJECTHEADER.FILEENDPOSITION AS  NCCIELEMMENTLENGTH," +
    " HEADERTYPE.NAME AS SUBJECTHEADER" +
    " FROM WCSTREF.NCCISUBJECTHEADER SUBJECTHEADER" +
    " JOIN WCSTREF.NCCIELEMENTDETAILS ELEMENTDETAILS ON ELEMENTDETAILS.ID = SUBJECTHEADER.NCCIELEMENTDETAILSID" +
    " JOIN WCSTREF.NCCISTATETOSUBJECTHEADER STATETOSUBJECTHEADER ON STATETOSUBJECTHEADER.NCCISUBJECTHEADER = SUBJECTHEADER.ID" +
    " JOIN WCSTREF.NCCI_STATE STATEES ON STATETOSUBJECTHEADER.STATE = STATEES.ID"+
    " JOIN WCSTREF.NCCISUBJECTHEADERTYPE HEADERTYPE ON HEADERTYPE.ID =  SUBJECTHEADER.NCCISUBJECTHEADERNAME"+
    " WHERE STATEES.TYPECODE = ?;";

    public static String bySubjectHeader =
    "SELECT" +
    " ELEMENTDETAILS.WCSTATHANDBOOKNAME AS NCCIELEMENTNAME," +
    " SUBJECTHEADER.FILESTARTPOSITION AS NCCIELEMENTOFFSET," +
    " SUBJECTHEADER.FILEENDPOSITION AS  NCCIELEMMENTLENGTH," +
    " HEADERTYPE.NAME AS SUBJECTHEADER" +
    " FROM WCSTREF.NCCISUBJECTHEADER SUBJECTHEADER" +
    " JOIN WCSTREF.NCCIELEMENTDETAILS ELEMENTDETAILS ON ELEMENTDETAILS.ID = SUBJECTHEADER.NCCIELEMENTDETAILSID" +
    " LEFT JOIN WCSTREF.NCCISTATETOSUBJECTHEADER STATETOSUBJECTHEADER ON STATETOSUBJECTHEADER.NCCISUBJECTHEADER = SUBJECTHEADER.ID" +
    " JOIN WCSTREF.NCCI_STATE STATEES ON STATETOSUBJECTHEADER.STATE = STATEES.ID" +
    " JOIN WCSTREF.NCCISUBJECTHEADERTYPE HEADERTYPE ON HEADERTYPE.ID =  SUBJECTHEADER.NCCISUBJECTHEADERNAME" +
    " WHERE HEADERTYPE.NAME = ?" +
    " ORDER BY HEADERTYPE.RECORD_TYPE, SUBJECTHEADER.FILESTARTPOSITION;";

    public static String transmission = "SELECT TOP 1 ${columns} FROM [WCSTAT].[TRANSMISSION] ORDER BY UPDATE_TIME DESC;";

    public static String newTransmissionEntry(java.util.Set<String> columns){
       String query = "INSERT INTO [WCSTAT].[TRANSMISSION] (";
       String cols = null;
       String vars = null;
        for (String col :columns) {
          if(!col.equals("ID")){
              if(cols == null){
                  cols = col;
              }else{
                  cols = cols + ", " + col ;
              }
              if(vars == null){
                  vars = "?";
              }else{
                  vars = vars + ",?";
              }
          }
        }
        query =  query + cols + " ) VALUES ( ";
        query = query + vars + " );";
       return query;
    }
    public static String getSubjectHeaderByRecodeTypeCode = "SELECT TYPECODE, RECORD_TYPE, RECORD_NUMBER_LENGTH, RECORD_NUMBER_START_POSITION FROM [WCSTREF].[NCCISUBJECTHEADERTYPE] WHERE TYPECODE = ?;";

    public static String subjectHeaderByState =
    "SELECT SUBJECTHEADER.TYPECODE FROM [WCSTREF].[NCCISTATEREPORT] REPORTTOSTATE " +
            "JOIN [WCSTREF].[NCCIREPORT] REPORT ON REPORTTOSTATE.REPORT = REPORT.ID " +
            "JOIN [WCSTREF].[NCCISUBJECTHEADERTYPE] SUBJECTHEADER ON SUBJECTHEADER.ID =  REPORTTOSTATE.NCCISUBJECTHEADERNAME " +
            "JOIN [WCSTREF].[NCCI_STATE] NCCISTATE ON REPORTTOSTATE.STATE =NCCISTATE.ID " +
            "WHERE " +
            "NCCISTATE.TYPECODE = ? " +
            "AND " +
            "REPORT.TYPECODE = ? " +
            "ORDER BY SUBJECTHEADER.RECORD_TYPE;";
     /*"SELECT SUBJECTHEADER.TYPECODE FROM [WCSTREF].[NCCISTATEREPORT] REPORTTOSTATE " +
             "JOIN [WCSTREF].[NCCI_STATE] NCCISTATE ON REPORTTOSTATE.STATE =NCCISTATE.ID " +
             "JOIN [WCSTREF].[NCCIREPORT] REPORT ON REPORTTOSTATE.REPORT = REPORT.ID " +
             "JOIN [WCSTREF].[NCCISUBJECTHEADERTYPE] SUBJECTHEADER ON SUBJECTHEADER.ID =  REPORTTOSTATE.NCCISUBJECTHEADERNAME " +
             "WHERE NCCISTATE.TYPECODE = ? " +
             "AND REPORT.TYPECODE = ? " +
             "ORDER BY SUBJECTHEADER.RECORD_TYPE;";*/

}
