-- Create WCSTAT schema in [NCCI_WCSTAT_STAGING]
USE [NCCI_WCSTAT_STAGING];
	IF EXISTS (SELECT name FROM NCCI_WCSTAT_STAGING.sys.schemas WHERE name = N'WCSTAT')
		BEGIN
			PRINT 'Dropping the NCCI_WCSTAT_STAGING.WCSTAT schema'
			DROP SCHEMA [WCSTAT]
		END
			PRINT 'Creating the NCCI_WCSTAT_STAGING.WCSTAT schema';
			CREATE SCHEMA [WCSTAT] AUTHORIZATION [dbo];