USE [NCCI_WCSTAT_STAGING]
IF EXISTS (SELECT name FROM NCCI_WCSTAT_STAGING.sys.schemas WHERE name = N'WCSTREF')
		BEGIN
		PRINT 'Dropping the NCCI_WCSTAT_STAGING.WCSTREF schema'
			DROP SCHEMA [WCSTAT]
		END
			PRINT 'Creating the NCCI_WCSTAT_STAGING.WCSTREF schema';
		CREATE SCHEMA [WCSTREF] AUTHORIZATION [dbo];


