//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.23 at 07:45:34 PM CDT 
//


package subjectheadertypemodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the subjectheadertypemodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SubjectHeaderType_QNAME = new QName("http://guidewire.com/bc/gx/subjectheadertypemodel", "SubjectHeaderType");
    private final static QName _SubjectHeaderTypeSubjectHeading_QNAME = new QName("http://guidewire.com/bc/gx/subjectheadertypemodel", "SubjectHeading");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: subjectheadertypemodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SubjectHeaderType }
     * 
     */
    public SubjectHeaderType createSubjectHeaderType() {
        return new SubjectHeaderType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectHeaderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/subjectheadertypemodel", name = "SubjectHeaderType")
    public JAXBElement<SubjectHeaderType> createSubjectHeaderType(SubjectHeaderType value) {
        return new JAXBElement<SubjectHeaderType>(_SubjectHeaderType_QNAME, SubjectHeaderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://guidewire.com/bc/gx/subjectheadertypemodel", name = "SubjectHeading", scope = SubjectHeaderType.class)
    public JAXBElement<String> createSubjectHeaderTypeSubjectHeading(String value) {
        return new JAXBElement<String>(_SubjectHeaderTypeSubjectHeading_QNAME, String.class, SubjectHeaderType.class, value);
    }

}
